name: TestPlugin
main: com.gmail.kyrans19.TestPlugin.TestPlugin
version: 1.0-SNAPSHOT
author: GEOFAIRY
commands:
  smite:
    description: Places lightning on a target player or when the sender is looking.
    usage: /smite [player]
    permission: TestPlugin.smite
    permission-message: You lack the required permissions for this command
  kill:
    description: Kills the user or a target player.
    usage: /kill [player]
    permission: TestPlugin.kill.self
    permission-message: You lack the required permissions for this command
  tpr:
    description: Requests a teleport to a specified player
    usage: /tpr [player]
    permission: TestPlugin.teleport.request
    permission-message: You lack the required permissions for this command
  tpaccept:
    description: Accepts a teleport request
    usage: /tpaccept
    permission: TestPlugin.teleport.accept
    permission-message: You lack the required permissions for this command
  tpdecline:
    description: Declines a teleport request
    usage: /tpdecline
    permission: TestPlugin.teleport.decline
    permission-message: You lack the required permissions for this command
  heal:
    description: Heals a target player by a given ammount or to max
    usage: /heal [amount] [player]
    permission: TestPlugin.heal
    permission-message: You lack the required permissions for this command
  spawn:
    description: Move the sender to the spawn
    usage: /spawn
    permission: TestPlugin.spawn
    permission-message: You lack the required permissions for this command

permission:
  TestPlugin.*:
    description: Gives acces to all TestPlugin commands
    children:
      TestPlugin.smite: true
      TestPlugin.kill.*: true
      TestPlugin.teleport.*: true
      TestPlugin.heal: true
      TestPlugin.spawn: true
  TestPlugin.smite:
    description: Allows a user to smite
    default: op
  TestPlugin.kill.*:
    description: Gives access to all TestPlugin.kill commands
    children:
      TestPlugin.kill.self: true
      TestPlugin.kill.other: true
  TestPlugin.kill.self:
    description: Allows a user to kill themselves
    default: true
  TestPlugin.kill.other:
    description: Allows a user to kill others
    default: op
  TestPlugin.teleport.*:
    description: Gives access to all TestPlugin.teleport commands
    children:
      TestPlugin.teleport.request: true
      TestPlugin.teleport.accept: true
      TestPlugin.teleport.decline: true
  TestPlugin.teleport.request:
    description: Allows a user to request a teleport
    default: true
  TestPlugin.teleport.accept:
    description: Accepts a teleport request
    default: true
  TestPlugin.teleport.decline:
    description: Accepts a teleport request
    default: true
  TestPlugin.heal:
    description: Heals a target player by a given ammount or to max
    default: true
  TestPlugin.spawn:
    description: Move the sender to the spawn
    default: true